version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: main
  ignore:
  - dependency-name: webpack
    versions:
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.16
  - dependency-name: css-loader
    versions:
    - 5.2.4
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.1.0
